blank_issues_enabled: false
contact_links:
  - name: Pineflow Documentation
    url: https://leonardofurnielis.github.io/pineflow/
    about: Please review the latest documentation before posting an issue.
