name: Linting

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.14"]
    steps:
      - uses: actions/checkout@v4

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "**/uv.lock"

      - name: install uv
        run: pipx install uv

      - name: install dependencies (dev)
        run: uv pip install --require-locked .[dev]

      - name: run linter
        shell: bash
        run: uv run ruff check .