name: Linting

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.14"]
    steps:
      - uses: actions/checkout@v4

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "**/uv.lock"

      - name: install uv
        run: pipx install uv

      - name: create uv venv
        run: uv venv create

      - name: activate venv and install dependencies (dev)
        shell: bash
        run: |
          source .venv/bin/activate
          uv pip install .[dev]

      - name: activate venv and run linter
        shell: bash
        run: |
          source .venv/bin/activate
          uv run ruff check .