name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main]

jobs:
  pages:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: 3.10.14
        cache: 'poetry'
    - name: install dependencies
      run: poetry install --with docs
    - name: running sphinx build
      run: poetry run sphinx-build -b html ./docs ./sphinx-pages
    - name: setup pages
      uses: actions/configure-pages@v4
    - name: upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./sphinx-pages
    - id: deployment
      name: deploy to github pages
      uses: actions/deploy-pages@v4
